# yaml-language-server: $schema=ownbrew.schema.json
version: '1.1'

binDir: "bin"
tapDir: ".ownbrew/tap"
#tempDir: ".ownbrew/tmp"
#cellarDir: ".ownbrew/bin"
tempDir: '/Users/franklin/.local/share/ownbrew/tmp'
cellarDir: '/Users/franklin/.local/share/ownbrew/bin'
packages:
  ## https://github.com/golangci/golangci-lint/releases
  - name: golangci-lint
    tags: [ci]
    tap: foomo/tap/golangci/golangci-lint
    version: 1.61.0
  ## https://github.com/go-courier/husky/releases
  - name: husky
    tap: foomo/tap/go-courier/husky
    version: 1.8.1
